"""Semantic-locality reports — the unaddressed-assertion sheet and the census CLI.

## What this is

The operator half S7/S9/S11 left in the legacy `foundry_locality` shell:
`--census` (coverage over live assertions, printed) and `--report` (the list of
assertions the backfill will NOT address, grouped by reason, written as JSON and
Markdown behind two cross-checks and a ×2 determinism gate). S13 moved it here.
Every line, byte, check order and refusal message is the shell's.

## What this is NOT

* **Not the address law or its codebook binding.** `resolve`, the statuses and
  owning headers are `mtj_foundry.mtg.shapes.locality`; the census and the
  unaddressed walk over live assertions are `mtj_foundry.codebook_locality`.
  The composition boundary calls both — through its halting resolver — and
  hands the results here.
* **Not a reader, writer or process boundary.** The corpus load, the codebook
  reads, the output paths, both writers, the `generated_by` provenance string
  and the historic `STOP — …` come from the composition boundary.
"""

from __future__ import annotations

import argparse
import dataclasses
import json
from collections import Counter
from pathlib import Path
from typing import Callable

__all__ = ["LocalityReportContext", "REASON_NOTES", "census_lines", "cmd_report",
           "render_unaddressed_md", "run"]

# Why each reason is unaddressed, and what a human would have to do about it.
# Prose, not vocabulary: none of these strings is a ratified token.
REASON_NOTES = {
    "AMBIGUOUS": ("the quote appears in more than one paragraph, so no "
                  "deterministic rule picks one. Dominated by short repeated "
                  "riders. FIX: narrow the evidence quote to the paragraph "
                  "that actually proves the axis."),
    "SPAN": ("the quote legitimately covers a contiguous run of paragraphs "
             "(A2). The evidence is LOCATED but the fact has no single owner. "
             "FIX: usually none needed -- a modal block quote is honest "
             "evidence; narrow it only if the axis is about one mode."),
    "UNRESOLVED": ("the quote matches no text in the current corpus snapshot. "
                   "Near-noise today. FIX: re-check the quote against the "
                   "card; addresses are snapshot-relative and re-derived."),
    "QUOTELESS": ("the assertion carries no quote at all (the A3 "
                  "legacy-captain-seed exemption). An address is DERIVED from "
                  "a quote, so there is nothing to resolve. FIX: record the "
                  "evidence quote; this is a provenance gap, not a locality "
                  "one."),
}


@dataclasses.dataclass(frozen=True)
class LocalityReportContext:
    description: str
    report_help: str
    generated_by: str
    load_cards: Callable[[], dict]
    census: Callable[[dict], dict]
    unaddressed_rows: Callable[[dict], list]
    json_path: Path
    md_path: Path
    write_json: Callable[[Path, dict], None]
    write_text: Callable[[Path, str], None]
    stop: Callable[[str], None]


def render_unaddressed_md(rows: list, totals: dict, generated_by: str) -> str:
    """The human-readable sheet. Pure function of `rows` -- determinism ×2."""
    by_reason = Counter(r["reason"] for r in rows)
    out = [
        "# SEMANTIC LOCALITY — the unaddressed assertions",
        "",
        f"Generated by `python3 {generated_by}`.",
        "**Regenerate rather than edit**; this file is gitignored and local.",
        "",
        "An unaddressed assertion is **fully valid card-level evidence** "
        "(ratified 2026-08-13).",
        "It simply cannot prove that its fact co-occurs in the same semantic "
        "unit with another.",
        "Nothing here is a defect by default — read the FIX note per reason.",
        "",
        f"- assertions on active axes: **{totals['assertions']:,}**",
        f"- addressed (semantic OWNER): **{totals['owned']:,}**",
        f"- **unaddressed: {len(rows):,}**",
        "",
        "| reason | n | what it means |",
        "|---|--:|---|",
    ]
    for reason in sorted(by_reason):
        out.append(f"| `{reason}` | {by_reason[reason]} | "
                   f"{REASON_NOTES.get(reason, '')} |")
    out.append("")
    for reason in sorted(by_reason):
        out += [f"## {reason} — {by_reason[reason]}", "",
                "| axis | card | class | source_ref | quote |",
                "|---|---|---|---|---|"]
        for r in (x for x in rows if x["reason"] == reason):
            q = r["quote"].replace("\n", " ⏎ ").replace("|", "\\|")
            if len(q) > 160:
                q = q[:157] + "…"
            out.append(f"| `{r['axis']}` | {r['card'].replace('|', '')} | "
                       f"{r['class']} | `{r['source_ref']}` | {q} |")
        out.append("")
    return "\n".join(out) + "\n"


def cmd_report(cards, ctx: LocalityReportContext) -> int:
    """Writes the two artifacts, with determinism ×2 byte-identical."""
    totals = ctx.census(cards)
    rows = ctx.unaddressed_rows(cards)

    # The reporter's own conservation check. `census` and `unaddressed_rows`
    # walk the codebook independently, so a disagreement means one of them is
    # wrong -- exactly the "second measurement path" rule, wired in rather than
    # done once by hand.
    expected = (totals["assertions"] - totals["owned"])
    if len(rows) != expected:
        ctx.stop(f"reporter disagreement: census says {expected} assertions are "
                 f"unaddressed ({totals['assertions']} total - "
                 f"{totals['owned']} owned) but the row walk found "
                 f"{len(rows)}. Two independent walks of the same codebook must "
                 f"agree; refusing to write a sheet that contradicts the gate.")
    by_reason = Counter(r["reason"] for r in rows)
    if by_reason["SPAN"] != totals["span"] or by_reason["AMBIGUOUS"] != totals["ambiguous"]:
        ctx.stop(f"reporter disagreement per reason: rows {dict(by_reason)} vs "
                 f"census {totals}")

    payload = {"generated_by": ctx.generated_by,
               "totals": totals, "unaddressed": len(rows),
               "by_reason": dict(sorted(by_reason.items())), "rows": rows}
    md = render_unaddressed_md(rows, totals, ctx.generated_by)

    # Determinism ×2 on both artifacts, from a second independent build.
    rows2 = ctx.unaddressed_rows(cards)
    payload2 = {"generated_by": payload["generated_by"], "totals": ctx.census(cards),
                "unaddressed": len(rows2),
                "by_reason": dict(sorted(Counter(r["reason"] for r in rows2).items())),
                "rows": rows2}
    if json.dumps(payload, sort_keys=False) != json.dumps(payload2, sort_keys=False):
        ctx.stop("determinism gate FAILED — two builds of the unaddressed "
                 "report differ")
    if render_unaddressed_md(rows2, payload2["totals"], ctx.generated_by) != md:
        ctx.stop("determinism gate FAILED — two renders of the unaddressed "
                 "sheet differ")

    ctx.write_json(ctx.json_path, payload)
    ctx.write_text(ctx.md_path, md)
    print(f"determinism ×2 byte-identical on both artifacts")
    print(f"wrote {ctx.json_path}")
    print(f"wrote {ctx.md_path}")
    print(f"\n{totals['assertions']:,} assertions on active axes · "
          f"{totals['owned']:,} addressed · {len(rows):,} UNADDRESSED")
    for reason in sorted(by_reason):
        print(f"    {reason:12}: {by_reason[reason]:>4}")
    return 0


def census_lines(m: dict) -> list:
    q = max(m["quoted"], 1)
    located = m["owned"] + m["span"]
    return [
        f"\nlocality census — {m['assertions']:,} assertions, "
        f"{m['quoted']:,} quoted, {m['quoteless']:,} quoteless",
        f"    semantic OWNER      : {m['owned']:,}  "
        f"({100 * m['owned'] / q:.2f}% of quoted)",
        f"    evidence LOCATED    : {located:,}  "
        f"({100 * located / q:.2f}% of quoted)   <- a different question",
        f"    span                : {m['span']:,}",
        f"    ambiguous           : {m['ambiguous']:,}",
        f"    unresolved          : {m['unresolved']:,}",
        f"  STORED in the codebook (a different question again)",
        f"    addressed           : {m['stored_owned']:,}",
        f"    stored_mismatch     : {m['stored_mismatch']:,}   "
        f"<- stored address disagrees with the resolver today",
        f"    addressable_missing : {m['addressable_missing']:,}   "
        f"<- resolver says OWNER but nothing is stored (must be 0)",
    ]


def build_parser(description: str, report_help: str) -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(
        description=description,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--census", action="store_true")
    ap.add_argument("--report", action="store_true", help=report_help)
    return ap


def run(argv, ctx: LocalityReportContext) -> int:
    args = build_parser(ctx.description, ctx.report_help).parse_args(argv)

    cards = ctx.load_cards()

    if args.report:
        return cmd_report(cards, ctx)

    if args.census:
        for line in census_lines(ctx.census(cards)):
            print(line)
    return 0
